# Generated by Django 3.0.6 on 2020-06-04 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_todoitem_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='TodoUser',
        ),
    ]
