# Generated by Django 3.0.7 on 2020-06-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='defaultt.jpg', upload_to='bio_pics'),
        ),
    ]
