# Generated by Django 3.0.7 on 2020-06-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='todo_default.jpeg', upload_to='bio_pics'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='text',
            field=models.TextField(default='', unique=True),
        ),
    ]
