# Generated by Django 3.0.7 on 2020-06-09 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0007_auto_20200609_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(help_text='Enter your email here', max_length=254, null=True, unique=True),
        ),
    ]
