# Generated by Django 3.0.7 on 2020-06-10 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0008_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
